language: node_js
node_js:
  - "lts/*"
git:
  lfs_skip_smudge: true
script:
  - yarn travis
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
notifications:
  email: false
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  local-dir: "dist"
  allow-empty-commit: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch:
      - v2/main
      - master