language: node_js
node_js:
  - "lts/*"
git:
  lfs_skip_smudge: true
script:
  - yarn lint
  - yarn build
deploy:
  skip-cleanup: true
  provider: surge
  project: ./dist/
  domain: app.smart-light.ga
cache: yarn
