language: node_js
node_js:
  - "lts/*"
git:
  lfs_skip_smudge: true
script:
  - npm run lint
  - npm run build
deploy:
  skip-cleanup: true
  provider: surge
  project: ./dist/
  domain: app.smart-light.ga
cache: npm
