on:
  push:
    branches:
      - master
name: Process TODO comments
jobs:
  collectTODO:
    name: Collect TODO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Collect TODO
        uses: dtinth/todo-actions@v0.2.0
        env:
          GITHUB_REPO_DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
