name: Process TODO comments
on:
  push:
    branches:
      - master
jobs:
  collectTODO:
    name: Collect TODO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: checkout
        run: |
          export BRANCH=${GITHUB_REF/refs\/heads\/}
          echo "BRANCH: $BRANCH"
          git checkout $BRANCH
      - name: Collect TODO
        uses: dtinth/todo-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
