name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout
      run: |
        export BRANCH=${GITHUB_REF/\/refs\/heads\/}
        git checkout $BRANCH
        git reset --hard $GITHUB_SHA
    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TODO_ACTIONS_MONGO_URL:  ${{ secrets.TODO_ACTIONS_MONGO_URL }}
