name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      run: |
        export BRANCH=${GITHUB_REF/refs\/heads\/}
        echo "REPO: $GITHUB_REPOSITORY"
        echo "BRANCH: $BRANCH"
        git clone --branch=$BRANCH https://github.com/$GITHUB_REPOSITORY
        git reset --hard $GITHUB_SHA
    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TODO_ACTIONS_MONGO_URL:  ${{ secrets.TODO_ACTIONS_MONGO_URL }}
